services:
  grafana:
    image: k0rventen/apple-health-grafana-grafana:rolling
    ports:
    - 3000:3000
  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    image: k0rventen/apple-health-grafana-ingester:v0.4.0
    volumes:
    - ./file:/export.zip

volumes:
  influx-data:
