name: Build an image for each non-main branch with tag :<branch_name>

permissions:
  contents: write

on:
  push:
    branches:
      - '**'      # matches every branch
      - '!main'   # excludes master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      -
        name: Docker build & push - ingester
        uses: docker/build-push-action@v4
        with:
          context: ./ingester
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.repository }}-ingester:${{ env.GITHUB_REF_SLUG }}
      -
        name: Docker build & push - grafana
        uses: docker/build-push-action@v4
        with:
          context: ./grafana
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.repository }}-grafana:${{ env.GITHUB_REF_SLUG }}
